# 1. Cấu hình kết nối Oracle Database
# Cổng mặc định của Oracle là 1521, Tên dịch vụ mặc định của bản Free là FREEPDB1
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
# Tài khoản đăng nhập database (Lúc cài Oracle bạn đăng nhập bằng tài khoản gì, thường là system)
spring.datasource.username=QL_CONG_VIEC
# THAY THẾ bằng mật khẩu bạn đã đặt khi cài đặt Oracle Database:
spring.datasource.password=cuong2004
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 2. Cấu hình JPA / Hibernate tự động tạo bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect